# CI for Aztec Network Scenarios.
# Triggered by network-deployments event, which is emitted by ci3.yml when a tagged release passes "normal" CI.
#
name: Test Network Scenarios

on:
  repository_dispatch:
    types:
      - network-deployments

concurrency:
  group: network-scenarios-${{ github.event.client_payload.major_version }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      #############
      # Prepare Env
      #############
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.client_payload.sha }}
          persist-credentials: false
      - name: Setup
        run: |
          # Ensure we can SSH into the spot instances we request.
          mkdir -p ~/.ssh
          echo ${{ secrets.BUILD_INSTANCE_SSH_KEY }} | base64 --decode > ~/.ssh/build_instance_key
          chmod 600 ~/.ssh/build_instance_key
          sudo apt install -y --no-install-recommends redis-tools parallel

      - name: Prepare GCP key
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" | base64 -w 0 > gcp_sa_key.b64
          echo "GCP_SA_KEY_B64=$(cat gcp_sa_key.b64)" >> $GITHUB_ENV

      # makes more sense to write the env file here

      #############
      # Run
      #############
      - name: Run
        if: steps.ci_cache.outputs.cache-hit != 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.AZTEC_BOT_GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # Nightly test env vars.
          GCP_SA_KEY_B64: ${{ env.GCP_SA_KEY_B64 }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          NAMESPACE: "v${{ github.event.client_payload.major_version }}-scenario"
          AZTEC_DOCKER_IMAGE: "aztecprotocol/aztec:${{ github.event.client_payload.semver }}"
        run: |
          exec ./ci.sh deploy-staging-networks
